FROM golang:alpine AS builder
WORKDIR /service
ADD ./service /service
ADD .git /service
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.io
RUN apk --no-cache add git
RUN VERSION=$(git describe --abbrev=0 --tags) && go build -ldflags="-X V2RayA/global.Version=${VERSION:1}" -o V2RayA .


FROM alpine:latest
RUN apk --no-cache add iptables
WORKDIR /service
COPY --from=builder /service/V2RayA .
ENV GIN_MODE=release
EXPOSE 2017
ENTRYPOINT "./V2RayA"
