FROM golang:alpine AS builder
ADD service /build/service
ADD cmd/moona /build/cmd/moona
WORKDIR /build/cmd/moona
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.io
RUN go build -o moona .

FROM v2fly/v2fly-core AS v2ray
COPY --from=builder /build/cmd/moona/moona /usr/bin/
ENV GIN_MODE=release
ENTRYPOINT ["moona"]
