FROM node:lts-alpine AS builder
ADD gui /gui
WORKDIR /gui
RUN yarn config set registry https://registry.npm.taobao.org
RUN yarn config set sass_binary_site https://cdn.npm.taobao.org/dist/node-sass
RUN yarn
RUN yarn build

FROM nginx:stable-alpine
COPY --from=builder /web /usr/share/nginx/html
EXPOSE 80
