FROM golang:alpine
RUN apk --no-cache add iptables git
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn
RUN go get github.com/codegangsta/gin
WORKDIR /service
ENV CONFIG=../config.json
ENV GIN_BIN=../V2RayA
ENV GIN_GUILD_ARGS="-o ${GIN_BIN}"
EXPOSE 2017
ENTRYPOINT gin -a 2017 -i run
