// Generates src/assets/lucide-font.css from lucide-static's font CSS with the
// @font-face trimmed to the single woff source. The upstream CSS references
// eot/ttf/svg/woff2 as well, which makes Vite emit ~23 MB of unused font
// files (the SVG font alone is ~20 MB). woff is supported by every browser
// since IE9.
//
// Re-runs automatically before `yarn build` / `yarn serve` (pre scripts in
// package.json), so a lucide-static upgrade stays in sync.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const src = fileURLToPath(
  new URL("../node_modules/lucide-static/font/lucide.css", import.meta.url)
);
const dst = fileURLToPath(
  new URL("../src/assets/lucide-font.css", import.meta.url)
);

const css = readFileSync(src, "utf8");
const face = css.match(/@font-face\s*\{[\s\S]*?\}/);
if (!face) {
  throw new Error("lucide-font: @font-face block not found in lucide.css");
}

const trimmed = css.replace(
  face[0],
  `@font-face {
  font-family: "lucide";
  /* bare package path, resolved by Vite to node_modules/lucide-static */
  src: url("lucide-static/font/lucide.woff") format("woff");
  font-weight: normal;
  font-style: normal;
}`
);

writeFileSync(
  dst,
  `/* AUTO-GENERATED by scripts/lucide-font.mjs from lucide-static/font/lucide.css.
 * Do not edit; only the woff webfont format is kept on purpose. */\n\n` +
    trimmed
);
console.log("lucide-font: wrote", dst);
