// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.2
// source: config.proto

package tunmips

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Config is the "tun-mips" inbound: a TUN device the core owns, driven by a
// user-space IP stack. The service side manages routes; the core creates
// the device and assigns its addresses.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Interface name. On macOS "utun" lets the kernel pick the unit.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mtu  uint32 `protobuf:"varint,2,opt,name=mtu,proto3" json:"mtu,omitempty"`
	// Operating-system side IPv4 address with prefix, e.g. "10.0.85.2/30".
	Address4 string `protobuf:"bytes,3,opt,name=address4,proto3" json:"address4,omitempty"`
	// Optional IPv6 address with prefix; empty disables IPv6 on the device.
	Address6 string `protobuf:"bytes,4,opt,name=address6,proto3" json:"address6,omitempty"`
	// host:port of the core's DNS module; port-53 flows to non-local
	// resolvers are relayed there.
	DnsTarget string `protobuf:"bytes,5,opt,name=dns_target,json=dnsTarget,proto3" json:"dns_target,omitempty"`
	// Executable basenames whose flows bypass the proxy.
	ExcludeProcesses []string `protobuf:"bytes,6,rep,name=exclude_processes,json=excludeProcesses,proto3" json:"exclude_processes,omitempty"`
	// PIDs whose flows always bypass the proxy (v2rayA and the core itself).
	SelfPids []uint32 `protobuf:"varint,7,rep,packed,name=self_pids,json=selfPids,proto3" json:"self_pids,omitempty"`
	// Outbound tag used for excluded flows; "direct" when empty.
	DirectTag     string `protobuf:"bytes,8,opt,name=direct_tag,json=directTag,proto3" json:"direct_tag,omitempty"`
	UserLevel     uint32 `protobuf:"varint,9,opt,name=user_level,json=userLevel,proto3" json:"user_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Config) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *Config) GetAddress4() string {
	if x != nil {
		return x.Address4
	}
	return ""
}

func (x *Config) GetAddress6() string {
	if x != nil {
		return x.Address6
	}
	return ""
}

func (x *Config) GetDnsTarget() string {
	if x != nil {
		return x.DnsTarget
	}
	return ""
}

func (x *Config) GetExcludeProcesses() []string {
	if x != nil {
		return x.ExcludeProcesses
	}
	return nil
}

func (x *Config) GetSelfPids() []uint32 {
	if x != nil {
		return x.SelfPids
	}
	return nil
}

func (x *Config) GetDirectTag() string {
	if x != nil {
		return x.DirectTag
	}
	return ""
}

func (x *Config) GetUserLevel() uint32 {
	if x != nil {
		return x.UserLevel
	}
	return 0
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x14v2raya.proxy.tunmips\"\x8d\x02\n" +
	"\x06Config\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03mtu\x18\x02 \x01(\rR\x03mtu\x12\x1a\n" +
	"\baddress4\x18\x03 \x01(\tR\baddress4\x12\x1a\n" +
	"\baddress6\x18\x04 \x01(\tR\baddress6\x12\x1d\n" +
	"\n" +
	"dns_target\x18\x05 \x01(\tR\tdnsTarget\x12+\n" +
	"\x11exclude_processes\x18\x06 \x03(\tR\x10excludeProcesses\x12\x1b\n" +
	"\tself_pids\x18\a \x03(\rR\bselfPids\x12\x1d\n" +
	"\n" +
	"direct_tag\x18\b \x01(\tR\tdirectTag\x12\x1d\n" +
	"\n" +
	"user_level\x18\t \x01(\rR\tuserLevelB2Z0github.com/v2rayA/v2raya-core/hint/proxy/tunmipsb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_config_proto_goTypes = []any{
	(*Config)(nil), // 0: v2raya.proxy.tunmips.Config
}
var file_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
