// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: hint/proxy/hysteria2/config.proto

package hysteria2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server address in "host:port" format
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Authentication password
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// TLS SNI override (optional)
	Sni string `protobuf:"bytes,3,opt,name=sni,proto3" json:"sni,omitempty"`
	// Allow insecure TLS (skip verification)
	AllowInsecure bool `protobuf:"varint,4,opt,name=allow_insecure,json=allowInsecure,proto3" json:"allow_insecure,omitempty"`
	// Pinned certificate chain SHA256 hash (optional)
	PinnedCertchainSha256 string `protobuf:"bytes,5,opt,name=pinned_certchain_sha256,json=pinnedCertchainSha256,proto3" json:"pinned_certchain_sha256,omitempty"`
	// Obfuscation type: "none" or "salamander"
	Obfs string `protobuf:"bytes,6,opt,name=obfs,proto3" json:"obfs,omitempty"`
	// Salamander obfuscation password
	ObfsPassword string `protobuf:"bytes,7,opt,name=obfs_password,json=obfsPassword,proto3" json:"obfs_password,omitempty"`
	// Upload bandwidth limit (Mbps, 0 = unlimited)
	UpMbps uint32 `protobuf:"varint,8,opt,name=up_mbps,json=upMbps,proto3" json:"up_mbps,omitempty"`
	// Download bandwidth limit (Mbps, 0 = unlimited)
	DownMbps          uint32 `protobuf:"varint,9,opt,name=down_mbps,json=downMbps,proto3" json:"down_mbps,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_hint_proxy_hysteria2_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_hint_proxy_hysteria2_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_hint_proxy_hysteria2_config_proto_rawDescGZIP(), []int{0}
}

func (x *ClientConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ClientConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ClientConfig) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *ClientConfig) GetAllowInsecure() bool {
	if x != nil {
		return x.AllowInsecure
	}
	return false
}

func (x *ClientConfig) GetPinnedCertchainSha256() string {
	if x != nil {
		return x.PinnedCertchainSha256
	}
	return ""
}

func (x *ClientConfig) GetObfs() string {
	if x != nil {
		return x.Obfs
	}
	return ""
}

func (x *ClientConfig) GetObfsPassword() string {
	if x != nil {
		return x.ObfsPassword
	}
	return ""
}

func (x *ClientConfig) GetUpMbps() uint32 {
	if x != nil {
		return x.UpMbps
	}
	return 0
}

func (x *ClientConfig) GetDownMbps() uint32 {
	if x != nil {
		return x.DownMbps
	}
	return 0
}

var File_hint_proxy_hysteria2_config_proto protoreflect.FileDescriptor

const file_hint_proxy_hysteria2_config_proto_rawDesc = 	"\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\nm\x90AN\xc30\x10E\x15ZH2\xb4\x14,Q\xbc" +
	"#\xb0\xca\x86X\x8a\x80=\xed-\xba\xb1\x1c\xdb\xad-\xa5\xb6e;\x84\xdc\x8e\xa3\" +
	"xa1\xbaRW\xacF\xef\xe9\x8fF\xf3\xe1Ei\x13\x89\xf3\xf6g\"j\nQz\xcdZ\xc2\xad\x" +
	"d9\xebC\xe3\xbc\x8d\x16\xad\xbf[\xcf&\xd6\xa4Ps\t\xbd\xfef\xb0\xd8\xf6Z\x9a\" +
	"xb8Mq\xb4\x82\x9c\t\xe1e\x088\xab\xb2\xbaD\xf7P8\x16\xc2h\xbd\xc0W\xc9\xdc\x" +
	"c2,\x18\x8dg\t\xd6p\xc7\xfa\xde\x8eT\x9b \xf9\xe0%\x9eWY]\xa0gxr\xda\x18)(\x" +
	"97>r\xc5\xb4\xa1A\xb1\xf6\xe3\x13_\xa7\xc5\x05\xccm\xb7\x0f\xf8&\xd1#,OD/\xa" +
	"7\xf2\xa4W\x90\x0f\x8e\x1e;\x17pQe\xf5\x12=@)\xech\xce\xaa<\xa9\xcd\xfb\xae=" +
	"\xe8\xa8\x86\xae\xe1\xf6H\xd2\x9f_\xe7\xc1\xde\xb8\xf5\x92\xfc\xd7\xce\x1f\x" +
	"fe\xa5\x1d\xaa4\x01\x00\x00"

var (
	file_hint_proxy_hysteria2_config_proto_rawDescOnce sync.Once
	file_hint_proxy_hysteria2_config_proto_rawDescData []byte
)

func file_hint_proxy_hysteria2_config_proto_rawDescGZIP() []byte {
	file_hint_proxy_hysteria2_config_proto_rawDescOnce.Do(func() {
		file_hint_proxy_hysteria2_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hint_proxy_hysteria2_config_proto_rawDesc), len(file_hint_proxy_hysteria2_config_proto_rawDesc)))
	})
	return file_hint_proxy_hysteria2_config_proto_rawDescData
}

var file_hint_proxy_hysteria2_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hint_proxy_hysteria2_config_proto_goTypes = []any{
	(*ClientConfig)(nil), // 0: v2raya.proxy.hysteria2.ClientConfig
}
var file_hint_proxy_hysteria2_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hint_proxy_hysteria2_config_proto_init() }
func file_hint_proxy_hysteria2_config_proto_init() {
	if File_hint_proxy_hysteria2_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hint_proxy_hysteria2_config_proto_rawDesc), len(file_hint_proxy_hysteria2_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hint_proxy_hysteria2_config_proto_goTypes,
		DependencyIndexes: file_hint_proxy_hysteria2_config_proto_depIdxs,
		MessageInfos:      file_hint_proxy_hysteria2_config_proto_msgTypes,
	}.Build()
	File_hint_proxy_hysteria2_config_proto = out.File
	file_hint_proxy_hysteria2_config_proto_goTypes = nil
	file_hint_proxy_hysteria2_config_proto_depIdxs = nil
}
