// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: hint/proxy/juicity/config.proto

package juicity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server address in "host:port" format
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// User UUID
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Authentication password
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// TLS SNI override (optional)
	Sni string `protobuf:"bytes,4,opt,name=sni,proto3" json:"sni,omitempty"`
	// Allow insecure TLS (skip verification)
	AllowInsecure bool `protobuf:"varint,5,opt,name=allow_insecure,json=allowInsecure,proto3" json:"allow_insecure,omitempty"`
	// Congestion control algorithm: bbr, cubic, new_reno
	CongestionControl string `protobuf:"bytes,6,opt,name=congestion_control,json=congestionControl,proto3" json:"congestion_control,omitempty"`
	// Pinned certificate chain SHA256 hash (optional)
	PinnedCertchainSha256 string `protobuf:"bytes,7,opt,name=pinned_certchain_sha256,json=pinnedCertchainSha256,proto3" json:"pinned_certchain_sha256,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_hint_proxy_juicity_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_hint_proxy_juicity_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_hint_proxy_juicity_config_proto_rawDescGZIP(), []int{0}
}

func (x *ClientConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ClientConfig) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ClientConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ClientConfig) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *ClientConfig) GetAllowInsecure() bool {
	if x != nil {
		return x.AllowInsecure
	}
	return false
}

func (x *ClientConfig) GetCongestionControl() string {
	if x != nil {
		return x.CongestionControl
	}
	return ""
}

func (x *ClientConfig) GetPinnedCertchainSha256() string {
	if x != nil {
		return x.PinnedCertchainSha256
	}
	return ""
}

var File_hint_proxy_juicity_config_proto protoreflect.FileDescriptor

const file_hint_proxy_juicity_config_proto_rawDesc = "" +
	"\n" +
	"\x1fhint/proxy/juicity/config.proto\x12\x14v2raya.proxy.juicity\"\xf8\x01\n" +
	"\fClientConfig\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x10\n" +
	"\x03sni\x18\x04 \x01(\tR\x03sni\x12%\n" +
	"\x0eallow_insecure\x18\x05 \x01(\bR\rallowInsecure\x12-\n" +
	"\x12congestion_control\x18\x06 \x01(\tR\x11congestionControl\x126\n" +
	"\x17pinned_certchain_sha256\x18\a \x01(\tR\x15pinnedCertchainSha256B2Z0github.com/v2rayA/v2raya-core/hint/proxy/juicityb\x06proto3"

var (
	file_hint_proxy_juicity_config_proto_rawDescOnce sync.Once
	file_hint_proxy_juicity_config_proto_rawDescData []byte
)

func file_hint_proxy_juicity_config_proto_rawDescGZIP() []byte {
	file_hint_proxy_juicity_config_proto_rawDescOnce.Do(func() {
		file_hint_proxy_juicity_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hint_proxy_juicity_config_proto_rawDesc), len(file_hint_proxy_juicity_config_proto_rawDesc)))
	})
	return file_hint_proxy_juicity_config_proto_rawDescData
}

var file_hint_proxy_juicity_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hint_proxy_juicity_config_proto_goTypes = []any{
	(*ClientConfig)(nil), // 0: v2raya.proxy.juicity.ClientConfig
}
var file_hint_proxy_juicity_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hint_proxy_juicity_config_proto_init() }
func file_hint_proxy_juicity_config_proto_init() {
	if File_hint_proxy_juicity_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hint_proxy_juicity_config_proto_rawDesc), len(file_hint_proxy_juicity_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hint_proxy_juicity_config_proto_goTypes,
		DependencyIndexes: file_hint_proxy_juicity_config_proto_depIdxs,
		MessageInfos:      file_hint_proxy_juicity_config_proto_msgTypes,
	}.Build()
	File_hint_proxy_juicity_config_proto = out.File
	file_hint_proxy_juicity_config_proto_goTypes = nil
	file_hint_proxy_juicity_config_proto_depIdxs = nil
}
