name: Build & Release v2rayA beta

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  release:
    uses: ./.github/workflows/_release.yml
    with:
      tag: ${{ inputs.tag }}
      prerelease: true
      publish_downstream: false
    secrets: inherit
