name: Build & Release v2rayA beta

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  Build_v2rayA_Web:
    uses: ./.github/workflows/_build_web.yml
    with:
      upload_archive: true

  Compute_Version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.prep.outputs.VERSION }}
    steps:
    - name: Compute Version
      id: prep
      run: |
        tag=${{ inputs.tag }}
        version=$(echo $tag | sed 's/v//g')
        echo "VERSION=$version" >> $GITHUB_OUTPUT

  Build_v2rayA_Binaries:
    needs: [Build_v2rayA_Web, Compute_Version]
    uses: ./.github/workflows/_build_binaries.yml
    with:
      version: ${{ needs.Compute_Version.outputs.version }}

  Build_Windows_Installers:
    needs: [Build_v2rayA_Binaries, Compute_Version]
    uses: ./.github/workflows/_build_windows_installer.yml
    with:
      version: ${{ needs.Compute_Version.outputs.version }}

  Build_Linux_Packages:
    needs: [Build_v2rayA_Binaries, Compute_Version]
    uses: ./.github/workflows/_build_linux_packages.yml
    with:
      version: ${{ needs.Compute_Version.outputs.version }}

  GitHub_Release:
    runs-on: ubuntu-latest
    needs: [Build_v2rayA_Binaries, Build_Windows_Installers, Build_Linux_Packages]
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Check Version
      id: prep
      env:
        REF: ${{ inputs.tag }}
      run: |
        tag=${{ inputs.tag }}
        version=$(echo $tag | sed 's/v//g')
        echo "VERSION=$version" >> $GITHUB_OUTPUT
        echo "VERSION=$version" >> $GITHUB_ENV
    - name: Download Artifacts
      uses: actions/download-artifact@v8
      with:
        path: builds/
    - name: Move Files to Release Directory
      shell: bash
      run: |
        mkdir -p release
        for file in $(ls builds | grep -E "^installer|^v2raya"); do
          mv builds/$file/$file release/
        done
        mv builds/web.tar.gz/web.tar.gz release/
        for file in $(ls release); do
          sha256sum release/$file | awk '{print $1}' > release/$file.sha256.txt
        done
        ls -l release/
    - name: Compress Web Files
      shell: pwsh
      run: |
        Compress-Archive -Path ./builds/web/* -DestinationPath ./web.zip
        ((Get-FileHash ./web.zip).hash).ToLower() > web.zip.sha256.txt
        Move-Item ./web.zip ./release/web.zip
        Move-Item ./web.zip.sha256.txt ./release/web.zip.sha256.txt
    - name: Upload Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        Latest_Releases=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/v2rayA/v2rayA/releases/latest | jq -r '.tag_name')
        Latest_tag=v${{ steps.prep.outputs.VERSION }}
        if [ "$Latest_Releases" != "$Latest_tag" ]; then
          gh release create "v${{ steps.prep.outputs.VERSION }}" -t "v${{ steps.prep.outputs.VERSION }}" --generate-notes --prerelease
        fi
        gh release upload "v${{ steps.prep.outputs.VERSION }}" release/*
