name: Build & Release v2rayA

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: "The tag to release"
        required: true

jobs:
  release:
    uses: ./.github/workflows/_release.yml
    with:
      tag: ${{ inputs.tag }}
      prerelease: false
      publish_downstream: true
    secrets: inherit
